format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 0

[docker_context]
disabled = true

[git_branch]
symbol = "b:"

[git_commit]
tag_symbol = " t:"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[python]
symbol = "py "
pyenv_version_name = true

